config/routes.rb
Rails.application.routes.draw do

  root 'posts#index', as: 'home'

  get 'about' => 'pages#about'
  get 'posts/work' => 'posts#work'

  resources :posts

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, length: {minimum: 5}
  validates :body, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @bodya = 'ravno:= 1683'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "admin" , password: "123",
    except: [:index]

  def index

  end
  def work
    @post = Post.all
  end
  def new
    @post = Post.new
  end
  def show
    @post = Post.find(params[:id])
  end
  def edit
    @post = Post.find(params[:id])
  end
  def update
    @post = Post.find(params[:id])

    if (@post.update(post_params))
      redirect_to @post
    else
      render 'new'
    end
  end
  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_work_path
  end
  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)

    if (@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end
  private def post_params
    params.require(:post).permit(:title,:priorit,:pay_date,:body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simpletest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
      <h5 class="my-0 mr-md-auto font-weight-bold">Bogdan Brain</h5>
      <nav class="my-2 my-md-0 mr-md-3">
        <span class="p-2 text-dark"><%= link_to "Главная страница", home_path %></span>
        <span class="p-2 text-dark"><%= link_to "Задачи", posts_work_path %></span>
        <span class="p-2 text-dark"><%= link_to "Создание задачи", new_post_path %></span>
      </nav>
      <a class="btn btn-outline-primary" href="posts/work">Sign in</a>
      <a style="margin-left:1%" class="btn btn-outline-primary" href="posts/work">Sign up</a>
    </div>

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h2> About menu + <%= @bodya %> </h2>

app/views/posts/edit.html.erb
<h1 style="text-align:center;">Редактирование задачи!</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>

<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
  <div style="width: 50%;margin: auto;" class="alert alert-danger"> <%= msg %> </div>
  <% end %>
<% end %>

<div style="width: 50%;margin: auto;" >
   <div style="border: 4px ridge #CEE3F6;border-radius:10px">
    <div style="width: 100%;background:#CEF6F5;display: table;padding-bottom: 1%;padding-top: 1%">
      <h5 style="float: left;padding-left:7%;width: 43%; ">Заголовок:</h5>
      <h5 style="float: right;padding-right:7%;width: 43%;text-align: right; ">Исполнитель:</h5>
      <div style="float: left;padding-left:7%;width: 43%; "><%= f.text_field(:title,{:class => 'form-control'})  %></div>
      <div style="float: right;padding-right:7%;width: 43%;text-align: right; ">Sameluk Bogdan</div>
    </div>
    <div style="width: 100%;background:#CEF6EC;display: table;padding-top: 1%;" >
      <div style="width: 100%;background:#CEF6EC;display: table;">
        <h6 style="float: left;padding-left:13%;width: 37%; ">Приоритет:</h6>
        <h6 style="float: right;padding-right:13%;width: 37%;text-align: right; ">Срок оплаты:</h6>
        <div style="float: left;padding-left:10%;width: 35%; "><%= f.select :priorit, [["1 - very low", "1 - very low"], ["2 - low", "2 - low"], ["3 - standart", "3 - standart"], ["4 - high", "4 - high"] , ["5 - very high", "5 - very high"]], {}, {:class => 'form-control'}  %></div>
        <div style="float: right;padding-right:10%;width: 35%;text-align: right; "><%= f.date_field(:pay_date, {:class => 'form-control'}) %></div>
      </div>

        <h5 style=" text-align:center; ">Описание:</h5>
        <div style="width: 80%;margin:auto; "><%= f.text_area(:body, {:class => 'form-control'}) %></div>
        <div style="padding-left: 3%;padding-top: 1.5%;padding-bottom: 1.5% "><%= f.submit({:class => 'btn btn-success'}) %></div>
    </div>
  </div>
</div>

<% end %>

app/views/posts/index.html.erb
<div style="width: 75%;margin: auto;text-align:center;">
  <h1> Welcome! </h1>
  <div>Добро пожаловать на этот "замечательный" сервис для создания задач. Функционал сайта невероятно мал , но все же лучше чем ничего) Список задач которые были созданы - на странице "Задачи"</div>
  <div><b>Login</b> - Admin</div>
  <div><b>Password</b> - 123</div>
  <img src="biznes-plan08.jpg" alt="rss feed" />
</div>

app/views/posts/new.html.erb
<h1 style="text-align:center;">Создание задачи!</h1>
<%= form_for :post, url: posts_path do |f| %>

<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
  <div style="width: 50%;margin: auto;" class="alert alert-danger"> <%= msg %> </div>
  <% end %>
<% end %>

<div style="width: 50%;margin: auto;" >
   <div style="border: 4px ridge #CEE3F6;border-radius:10px">
    <div style="width: 100%;background:#CEF6F5;display: table;padding-bottom: 1%;padding-top: 1%">
      <h5 style="float: left;padding-left:7%;width: 43%; ">Заголовок:</h5>
      <h5 style="float: right;padding-right:7%;width: 43%;text-align: right; ">Исполнитель:</h5>
      <div style="float: left;padding-left:7%;width: 43%; "><%= f.text_field(:title,{:class => 'form-control'})  %></div>
      <div style="float: right;padding-right:7%;width: 43%;text-align: right; ">Sameluk Bogdan</div>
    </div>
    <div style="width: 100%;background:#CEF6EC;display: table;padding-top: 1%;" >
      <div style="width: 100%;background:#CEF6EC;display: table;">
        <h6 style="float: left;padding-left:13%;width: 37%; ">Приоритет:</h6>
        <h6 style="float: right;padding-right:13%;width: 37%;text-align: right; ">Срок оплаты:</h6>
        <div style="float: left;padding-left:10%;width: 35%; "><%= f.select :priorit, [["1 - very low", "1 - very low"], ["2 - low", "2 - low"], ["3 - standart", "3 - standart"], ["4 - high", "4 - high"] , ["5 - very high", "5 - very high"]], {}, {:class => 'form-control'}  %></div>
        <div style="float: right;padding-right:10%;width: 35%;text-align: right; "><%= f.date_field(:pay_date, {:class => 'form-control'}) %></div>
      </div>

        <h5 style=" text-align:center; ">Описание:</h5>
        <div style="width: 80%;margin:auto; "><%= f.text_area(:body, {:class => 'form-control'}) %></div>
        <div style="padding-left: 3%;padding-top: 1.5%;padding-bottom: 1.5% "><%= f.submit({:class => 'btn btn-success'}) %></div>
    </div>
  </div>
</div>

<% end %>

app/views/posts/show.html.erb
<div style="width: 50%;margin: auto;margin-bottom: 42px;">
		 	<div style="float: right; margin-right: 10px;text-align: right; background: #F2F2F2; border-top: 4px ridge #CEE3F6;border-left: 4px ridge #CEE3F6;border-right: 4px groove #CEE3F6;border-top-left-radius: 5px; border-top-right-radius: 5px;" ><%= link_to "Удалить", post_path(@post), method: :delete, data:{confirm: "Хотите удалить задачу?"} %></div>
		 	<div style="float: right; margin-right: 10px;text-align: right; background: #F2F2F2; border-top: 4px ridge #CEE3F6;border-left: 4px ridge #CEE3F6;border-right: 4px groove #CEE3F6;border-top-left-radius: 5px; border-top-right-radius: 5px;" ><a href=""><%= link_to "Редактировать", edit_post_path(@post) %></a></div>
	 	 </div>
<div style="width: 50%;margin: auto;" >
		 <div style="border: 4px ridge #CEE3F6;border-radius:10px">
			<div style="width: 100%;background:#CEF6F5;display: table;">
				<h5 style="float: left;padding-left:7%;width: 43%; ">Задача:</h5>
				<h5 style="float: right;padding-right:7%;width: 43%;text-align: right; ">Исполнитель:</h5>
				<div style="float: left;padding-left:7%;width: 43%; "><%= @post.title %></div>
				<div style="float: right;padding-right:7%;width: 43%;text-align: right; ">Sameluk Bogdan</div>
			</div>
			<div style="width: 100%;background:#CEF6EC;display: table;" >
				<div style="width: 100%;background:#CEF6EC;display: table;padding-top: 0.75%;">
					<h6 style="float: left;padding-left:13%;width: 37%; ">Приоритет:</h6>
					<h6 style="float: right;padding-right:13%;width: 37%;text-align: right; ">Срок оплаты:</h6>
					<div style="float: left;padding-left:15%;width: 35%; "><%= @post.priorit %></div>
					<div style="float: right;padding-right:15%;width: 35%;text-align: right; "><%= @post.pay_date %></div>
				</div>

					<h6 style=" text-align:center; ">Описание:</h6>
					<div style="padding-left: 3% "><%= @post.body %></div>
			</div>
		</div>
</div>

app/views/posts/work.html.erb
<h1 style="text-align:center;">It`s work</h1>
<div style="width: 50%;margin: auto;" >
	 <hr>
</div>

</div>
<% @post.each do |post| %>

<div style="width: 50%;margin: auto;" >
		 <div style="border: 4px ridge #CEE3F6;border-radius:10px">
			<div style="width: 100%;background:#CEF6F5;display: table;">
				<h5 style="float: left;padding-left:7%;width: 43%; ">Задача:</h5>
				<h5 style="float: right;padding-right:7%;width: 43%;text-align: right; ">Исполнитель:</h5>
				<div style="float: left;padding-left:7%;width: 43%; "><a href="<%= post.id %>"><%= post.title %></a></div>
				<div style="float: right;padding-right:7%;width: 43%;text-align: right; ">Sameluk Bogdan</div>
			</div>

		</div>
	<hr>
</div>

<% end %>